### ISSUE TITLE
codex

### ISSUE THREAD

**Issue by bueltge** [MarketPress/duesseldorf-child-starter#4]
In einigen Ecken mehr auf den Codex achten. Whitespace insbesondere.

Die langen Funktionsnamen sind gruselig, warum?

**Comment by Chrico** [comment]
Welche langen Funktionsnamen meinst du @bueltge ? Bereinigung via PHPStorm kommt gleich.

**Comment by bueltge** [comment]
functions.php beispielsweise, `duesseldorf_child_filter_duesseldorf_get_styles_add_stylesheets`

**Comment by Chrico** [comment]
Achso, ja, dass ist eigentlich "konform" mit der Architektur, aber tatsächlich etwas lang. Wobei sie dadurch ziemlich aussagekräftig wird. :-) Müssen wir mal in Step 2 überlegen, wie wir das sinnvoll gestalten können.

**Comment by bueltge** [comment]
Konform ja, aber unschön, vertandlich finde ich es nicht. Es macht dem Laien das Lesen schwer, finde ich, man ist erschlagen ohne den Hintergrund der Architektur, des Ziels.
